version: "3.5"
services:

  nginx-gen:
    build:
      context: ./nginx-gen
    command: -notify-sighup nginx-gen -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    env_file:
      - .env
    environment:
      - SSL_POLICY=${NGINX_GEN_SSL_POLICY}
    image: letsencrypt-nginx-proxy-companion/nginx-gen:latest
    networks:
      - letsencrypt-nginx-proxy-companion
      - external-network
    volumes:
      - ${DOCKER_SOCKET_PATH}:/tmp/docker.sock:ro
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_PATH}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

  nginx-letsencrypt:
    build:
      context: ./nginx-letsencrypt
    container_name: nginx-letsencrypt
    env_file:
      - .env
    environment:
      - DEFAULT_EMAIL=${NGINX_LETSENCRYPT_EMAIL}
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-web
    image: letsencrypt-nginx-proxy-companion/nginx-letsencrypt:latest
    networks:
      - letsencrypt-nginx-proxy-companion
      - external-network
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock:ro
      - ${NGINX_DATA_PATH}/acme.sh:/etc/acme.sh
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:rw
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

  nginx-web:
    build:
      context: ./nginx-web
    container_name: nginx-web
    env_file:
      - .env
    expose:
      - 80
      - 443
    image: letsencrypt-nginx-proxy-companion/nginx-web:latest
    networks:
      - letsencrypt-nginx-proxy-companion
      - external-network
    volumes:
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

networks:
  letsencrypt-nginx-proxy-companion:
    driver: bridge
    name: letsencrypt-nginx-proxy-companion

  external-network:
    external:
      name: ${EXTERNAL_NETWORK}
