version: "3.5"

services:
  nginx-gen:
    command: -notify-sighup ${PROJECT_NAME}-nginx-gen -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${PROJECT_NAME}-nginx-gen
    environment:
      - SSL_POLICY=${NGINX_GEN_SSL_POLICY}
    image: jwilder/docker-gen
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH}:/tmp/docker.sock:ro
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_PATH}/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

  nginx-letsencrypt:
    container_name: ${PROJECT_NAME}-nginx-letsencrypt
    environment:
      - DEFAULT_EMAIL=${NGINX_LETSENCRYPT_EMAIL}
      - NGINX_DOCKER_GEN_CONTAINER=${PROJECT_NAME}-nginx-gen
      - NGINX_PROXY_CONTAINER=${PROJECT_NAME}-nginx-web
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock:ro
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:rw
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

  nginx-web:
    container_name: ${PROJECT_NAME}-nginx-web
    image: nginx
    ports:
      - ${NGINX_WEB_HTTP_PORT}:80
      - ${NGINX_WEB_HTTPS_PORT}:443
    restart: unless-stopped
    volumes:
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d

networks:
  default:
    external:
      name: ${NETWORK}
