version: "3.5"
services:
  nginx-web:
    container_name: ${PROJECT_NAME}-nginx-web
    image: nginx
    networks:
      - docker-letsencrypt-nginx-proxy-companion
      - external-network
    ports:
      - ${NGINX_WEB_HTTP_PORT}:80
      - ${NGINX_WEB_HTTPS_PORT}:443
    restart: unless-stopped
    volumes:
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:ro
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d
