version: "3.5"
services:
  nginx-letsencrypt:
    container_name: ${PROJECT_NAME}-nginx-letsencrypt
    environment:
      - DEFAULT_EMAIL=${NGINX_LETSENCRYPT_EMAIL}
      - NGINX_DOCKER_GEN_CONTAINER=${PROJECT_NAME}-nginx-gen
      - NGINX_PROXY_CONTAINER=${PROJECT_NAME}-nginx-web
    image: jrcs/letsencrypt-nginx-proxy-companion
    networks:
      - docker-letsencrypt-nginx-proxy-companion
      - external-network
    restart: unless-stopped
    volumes:
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock:ro
      - ${NGINX_DATA_PATH}/certs:/etc/nginx/certs:rw
      - ${NGINX_DATA_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_DATA_PATH}/html:/usr/share/nginx/html
      - ${NGINX_DATA_PATH}/vhost.d:/etc/nginx/vhost.d
